### ISSUE TITLE
Question on Time Commitment to Complete Guide

### ISSUE THREAD

**Issue by CodeMargin** [P1xt/p1xt-guides#109]
I'm trying to set goals to complete various benchmarks of Computer Science and Programming - Version 4.0 and ultimately get a junior developer position. Any idea of a range of total hours you would anticipate it would take for a beginner allocating full 50 hour weeks to get through the entire program?

I have been considering a 7 month backend bootcamp instead of self-teaching and I am wondering how I can expect my knowledge base to compare to that if I complete this program wholeheartedly, and whether I might expect this curriculum would cover similar ground, more, or less.

**Comment by P1xt** [comment]
Unfortunately, yours is a completely subjective question. 

Have I seen highly motivated, incredibly driven, masters of determination and willpower finish the equivalent of the 'junior' section in a matter of a few months? 

Yes, absolutely. 

Have I seen other optimistic souls barely scratch the surface in triple the time. 

Unfortunately, also yes, absolutely.

I can't gauge for you how long it will take you. I don't know you. I don't know your personal level of commitment. I don't know how likely you are to get sidetracked tossing money at Udemy as soon as something gets tough. I don't know how much of your 50 hours per week will be spent on youtube hoping someone made a quick and easy video that'll magically save you some work.

You are the only one who has control over how long it will take you so my recommendation would be to give it your absolute all for two weeks, really push, really focus, keep track of anything you're doing that breaks your focus (and stop doing it) - and do your personal absolute best to push through and learn the absolute most you can in those 100 hours. Then, see how far you got - that will be your best gauge as to how long learning takes you personally.

**Comment by P1xt** [comment]
As to the second part of your question - if you complete through Tier 1 including a specialization, and don't half-arse it, you'll be on similar ground.

**Comment by P1xt** [comment]
If you progress into Tier 2 and complete it and another specialization, you'll be 'beyond'.

**Comment by P1xt** [comment]
My strong advice is this though - don't mess around wasting time you could spend learning trying to plan out schedules about what you will learn and when you'll learn it.

That is procrastination. It is valuable time you could have spent learning. It's extra mental bandwidth spent on worrying about learning instead of actually learning.

Decide that you are going to do this - then throw yourself into it, push every second of your learning time, learn as much as you can, as thoroughly as you can. And, then look back and see everything that you can accomplish if you focus on the learning.

If you are truly giving it your all, your progress will be the same whether you scheduled it or not anyway.

Give it two weeks just diving in and going for it - I highly doubt you'll be disappointed. That's what I've seen all of the most successful users of my guides do. The less successful, well, they spend more time thinking about learning than actually learning and eventually jump between every resource on the web and end up 3 years later hardly more qualified than when they started.

**Comment by CodeMargin** [comment]
That's what I was hoping to hear. I'm new enough to coding and computer science to truly not know what I need to know or even where to even start. I just know where I want to end up. 

Thank you for your response and advice. Here's to hoping I'm one of the people who picks it up quickly.
