### ISSUE TITLE
Question about tier programming project

### ISSUE THREAD

**Issue by dsaw** [P1xt/p1xt-guides#112]
In the tier programming project section, is it fine to pick a framework / library to do the projects? There doesn't seem to be any criteria in it as such.

**Comment by P1xt** [comment]
You can pick anything you want. The point of leaving them ambiguous is so that you have the opportunity to build something that interests you. That said, if you're doing the tier programming project as part of a specialization, the project should be aligned with that specialization (for instance: it should be a game if you're doing the game specialization, mobile app if you're doing the mobile app specialization, etc.)

Use whatever you want, frameworks, libraries, vanilla - build what you want, using what you want to learn and get good with.
