### ISSUE TITLE
Free Bootcamp for beginner

### ISSUE THREAD

**Issue by shahidnsu** [P1xt/p1xt-guides#127]
I think you should add this to your guide. frontendmasters.com has an absolute gem of free Bootcamp for beginner. The link is https://frontendmasters.com/bootcamp/

**Comment by P1xt** [comment]
While I agree that that may be an excellent resource, it teaches nearly the same material represented in Tier X by Khan Academy, which is doing double duty by not only providing a gentle introduction to those topics, but also easing learners into the Khan Academy platform which could prove quite useful to them throughout their learning journey.

Additionally, I'd prefer to stick with Khan Academy resources as I've found them consistently high quality, available, and free.

I wouldn't feel comfortable including the frontend masters bootcamp further in the guide as:

- It would be redundant to the Khan Academy resources
- It isn't a bootcamp in the same sense as the other resources I've included that fall under that umbrella (The Odin Project, App Academy, Full Stack Open) but rather an extremely basic introduction
- Frontend masters is typically a paid resource, while this intro may be free today, the resource was only made available this month. I would prefer some history to see that it remains free (and updated to remain relevant) before adding it.

I do have the resource bookmarked, but I'll not be adding it at this time due to the reasons listed above.
