### ISSUE TITLE
MongoDB course no longer offered. 

### ISSUE THREAD

**Issue by friendlyRobotFactory** [P1xt/p1xt-guides#17]
Hello, 
The course "Introduction to MongoDB using the MEAN stack" (https://www.edx.org/course/introduction-mongodb-using-mean-stack-mongodbx-m101x-0) appears to NO LONGER be available. 
Could you update the guides "job ready" and "cs-wd: comprehensive" to reflect that, and ideally provide an alternative? 

Thank You for all the hard work you did putting these guides together, and keep it up. 

Regards,

**Comment by P1xt** [comment]
I'll give them a couple weeks to see if they re-release it, it was available within the last week or so but sometimes when they put out a new version it becomes unavailable for a bit.

In the interim, the courses on mongodb university are even better than the edx course (though made by the same people) - the only downside with them is that they run on a schedule, rather than self-paced.

Here's a link in the meantime:

https://university.mongodb.com/courses/schedule

you want M101JS: MongoDB for Node.js Developers - the next round starts on October 17.

**Comment by P1xt** [comment]
I touched base with MongoDB University and confirmed that that course really is sunset. I've replaced it in the guides with two options, each which approaches the topic from a slightly different angle, students may pick one, the other, or both.

**Comment by friendlyRobotFactory** [comment]
Both look great. There were some noises being made by certain people on the old course that one can't follow Karpov's code as closely as one would like for this kind of course. Perhaps this will be an improvement after all. External pacing as opposed to self-pacing is a bit of a downside but certainly not a deal-breaker. 

Thanks for reacting so quickly and again I greatly appreciate the work you're doing here. Please keep at it. 

Kind Regards,

**Comment by P1xt** [comment]
If it weren't for the external pacing, I would have switched to the (I
believe) more substantial course on MongoDB University quite some time ago.
I think presenting two options is likely the best of both worlds, for those
who want to delve deep into the database, there's one option, for those who
prefer a more 'full stack' slant, there's another. This way I can have the
externally paced course I'd prefer in the guide, but alongside an
alternative for those who prefer not to wait for the next session.
