### ISSUE TITLE
Add this comment written by you on reddit to Readme or FAQ.

### ISSUE THREAD

**Issue by VishalBot1** [P1xt/p1xt-guides#172]
This [comment made by you](https://www.reddit.com/r/learnprogramming/comments/eunl6y/odin_project_vs_free_code_camp_vs_appacademyio_vs/fikd8sd?utm_source=share&utm_medium=web2x&context=3) is absolutely gold for someone who is just starting off. This gives a proper timeline and todo list for an aspiring developer.

**Comment by P1xt** [comment]
I can't really properly integrate that comment into a "for everybody" resource because it was narrowly focused on one person's circumstance and bandwidth.

Were I to add that into the readme or faq, I would suspect it would be more disheartening than motivating for folks who don't have wide open schedules like the OP in that thread I posted to. My whole comment on the thread was predicated on the premise of having "40 to 50 hours per week" available to study and wanting to make the most of that time. 

I suspect that having that much available time is a bit of a rarity and feel it might be a bit mean to suggest a completion schedule based on 40 hours/per week to folks who have far less time available. That would just be setting people up to be down  on themselves for not being able to meet milestones that are far too aggressive for their circumstance.
