### ISSUE TITLE
Can I replace CS50's Mobile App Development course?

### ISSUE THREAD

**Issue by mohdfareed** [P1xt/p1xt-guides#175]
Hi p1xt,

Do you think it is possible to replace [CS50's Mobile App Development](https://www.edx.org/course/cs50s-mobile-app-development-with-react-native) with [CS193p (Developing Applications for iOS using SwiftUI)](https://cs193p.sites.stanford.edu) or [iOS & Swift - The Complete iOS App Development Bootcamp](https://www.udemy.com/course/ios-13-app-development-bootcamp/) without missing on any concepts? If so, which would you recommend of the aforementioned? And if I did so, would the mobile app development specialization be redundant?

My goal is not set yet on getting into native iOS development, but I would like to get an idea of it.

Another side question. Which specialization would you recommend if I had to choose only one, [the Odin Project](https://www.theodinproject.com/paths/full-stack-javascript) or [Full Stack Open](https://fullstackopen.com/en/)?

Thanks a lot!

**Comment by P1xt** [comment]
My best advice:

Take everyone's advice as input, but make YOUR decision based on your personal goals. If you want to do native mobile app development instead of React native - then do that. It is your life. It is your goals. It is your decision.

I've laid out a path. My primary goal is to streamline the "what to learn" decision making process to help others not get stuck so much on the "what" part so they can get to the actual learning. Make the path yours by bending it to accommodate your needs.

I'd take the Stanford course were it me picking between the two native mobile courses. That particular Udemy instructor's courses are basic to the point of being a waste of your time.

If it were me, I'd pick Full Stack Open over Odin. That said, Odin is great - it's just easier and as a result teaches you less.
