### ISSUE TITLE
YDKJS: async and performance is not in the list

### ISSUE THREAD

**Issue by muubar** [P1xt/p1xt-guides#178]
Hi there!

first of all, I can't thank you enough for this guide, it literally changed my life 3 years ago.

I noticed that "YDKJS: async and performance" is not part of any tier's readings list? is this intentional? if so, could you please explain why you think we should omit it?

**Comment by P1xt** [comment]
That was absolutely not intentional and, in fact, I thought it was still in there. I've always had YDKJS in the list and must have missed copying that one into the new sequence the last time I revamped.

It should be in the latter tier that wraps up the YDKJS series. 

I'm making a mental note to go double check to see if any more of the new versions of YDKJS are out, then pop Async back into it's rightful spot.

Thanks so much for the catch!
