### ISSUE TITLE
Change in AppAcademy Curiculum

### ISSUE THREAD

**Issue by srithasriram30** [P1xt/p1xt-guides#181]
AppAcademy has recently (25 Apr 2022) changed to a different curriculum, Open V2. The older course is still available at [open.appacademy.io/login](https://open.appacademy.io/login). The differences between the two are here in the FAQ: https://appacademy.zendesk.com/hc/en-us/categories/360000981293-FAQ-App-Academy-Open

So my question is, should we continue with Open V1 or move on to Open V2?

**Comment by P1xt** [comment]
They have not changed to a new curriculum.

They actually have two curricula. The one I'm currently linking to (Ruby based) and a JavaScript/Python one as well. Both have been available to their paid students for quite some time and the JS/Python one was in beta for the open (free) students for about the last year. They moved the JS/Python open version onto a new platform a month or so ago and what you saw released yesterday was the result of that beta test. That test is not complete, at least I hope it isn't 'cause they just changed a perfectly nice dark theme into a (to my eyes) headache inducing light theme complete with two billion dropdowns and red on white links.

I've been watching the beta evolve and my general sense right now is:
- it DOES NOT MATTER which languages you're learning, the important part is learning the concepts, which both teach well
- The Ruby curriculum is fantastic and well worth your time
- The JS/PY curriculum is even better, not because of what languages it teaches but rather because it integrates a fair amount of spaced repetition and other pedagogy upgrades

I would happily recommend either to anyone wanting a robust introduction to programming.

I will not update this repository to include the JS/PY version as an option until it's actually completely available. Everything from about midway is "coming soon".

<img width="1005" alt="Screen Shot 2022-04-26 at 11 43 01 AM" src="https://userimages.githubusercontent.com/322175/165350739-a163dd63-975a-4732-9ab1-db3113fe34be.png">

Leaving this open because it IS on my radar to include the JS/PY version. I'm just not going to do that until it's actually complete.

**Comment by DamienAubrietJ** [comment]
They have published the latest modules

**Comment by P1xt** [comment]
Yeah, I saw that, letting the dust settle for a few days (and spot checking it myself to make sure there are no bugs that'd keep folks from finishing)

**Comment by DamienAubrietJ** [comment]
Yes, I tested the program it is less deep than the old one. The repetition and better it would be necessary to add the free books of the launchSchool.
sorry if ever my comments are weird I am a French developer, I used your deposit for some project of my school

**Comment by Aryan3212** [comment]
@P1xt Maybe we can add a note that even though there is a JS/Python alternative that is newer, the Ruby course is more in-depth?

**Comment by P1xt** [comment]
Note to self, update to the new curriculum, a/A has broken the old links.

**Comment by P1xt** [comment]
Extra note to self: Find time to recheck all links and update to the V2 a/A curriculum, it is outstanding!

**Comment by RAKAHH** [comment]
Hello P1xt I would like to know if I should choose v1 or v2 of openappacademy thank you in advance and thank you for your work.

**Comment by P1xt** [comment]
Personally, I enjoyed V1 more, it seemed to teach more of the more difficult topics and I felt that I learned more.

That said, if you're just starting out and value having contact with others who are going through the same curriculum as you (although they're not likely to be at the exact same lesson because everyone started on a different day and goes at a different pace) take V2. The discord is almost exclusively folks going through V2 and there are help channels there for if you get stuck so you can ask a question and (maybe, not guaranteed) someone will be able to help you. With V1 you pretty much need to be prepared to go it alone.

**Comment by RAKAHH** [comment]
Thanks, man, you're the best. I already have a few years of programming in c and asm ( I like roms ) I decided to learn the web with a program it's easier thanks to you again

**Comment by P1xt** [comment]
Unfortunately, a/A has really fallen behind with updates so I've elected to replace it with more current resources in the v5 revamp.

The v5 revamp went live with commit 352bfafcaa81f07186c96297e13e03de0f818fad
