### ISSUE TITLE
UC Berkeley CS61 series 

### ISSUE THREAD

**Issue by eldanieldev** [P1xt/p1xt-guides#186]
Have you considered including the Berkeley CS A/B/C  course series as part of the guide? 

Not sure if it would be redundant, but it comes highly recommended on learning-to-program forum posts.

**Comment by P1xt** [comment]
Sorry for the late reply. I wholeheartedly agree that the Berkeley courses are top notch, I'm just wary about adding them because Berkeley has a history of just shutting all their open source curriculum down without a lot of warning. They're not like MIT who keeps their open sourced courses available online pretty much forever (barring them finding out their Physics guru was sleezing his way into people's DMs.)
