### ISSUE TITLE
Update the course Introduction to Computer Science and Programming in Python

### ISSUE THREAD

**Issue by Sazid99246** [P1xt/p1xt-guides#210]
Hello, I have come to know that MIT OCW has updated their Intro to CS and Programming using Python course. Here is the link to the updated one: [Introduction to CS and Programming using Python](https://ocw.mit.edu/courses/6-100l-introduction-to-cs-and-programming-using-python-fall-2022/). Would you like to check it?

**Comment by P1xt** [comment]
I have seen that. I elected to stay with the 2016 version because:
- the material covers the same topics using the same python version
- I prefer the 2016 version formatting
- the follow up course ([Introduction to Computational Thinking and Data Science](https://ocw.mit.edu/courses/6-0002-introduction-to-computational-thinking-and-data-science-fall-2016/)) has not yet been updated and I would prefer consistency in the version of the two courses as a set.
