### ISSUE TITLE
Someone can create a Job Ready or Guidelines for iOS development?

### ISSUE THREAD

**Issue by quangnd-pgvn** [P1xt/p1xt-guides#43]
This repository is awesome! Currently, I'm on iOS path but I'm confused to follow. Anyone can help me?

**Comment by P1xt** [comment]
Sorry, I've considered making an iOS guide but decided against it. I endeavor to ensure that anybody, regardless of their financial circumstance, can pick up one of my guides so long as they have some computer with access to the internet (which presumably they'd have if they found this repo). If I created an iOS guide, it would have to start with "ok, first go out and drop some money on buying a Mac because Apple won't let you publish an app unless you build on a Mac" - and I'm not willing to do that.

You'll have to look elsewhere for iOS guides - they won't appear here until Apple decides to let me deploy an iOS app from my linux box.
