### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by RyRyMc** [P1xt/p1xt-guides#49]
Thanks for taking the time to read this, I really appreciate it. First off thanks you so much for all the work you have put into this. It is beyond helpful. 

I was just wanting to ask for what you would recommend. I work the night shift in Surveillance at a casino right now, but I don't like it. I want to work in computer programming. As I have looked at the guides I am pretty sure that my final goal I am aiming at would be becoming a data scientist. The study for that course is going to take a while, but I know it is what I want to do. This being said I want to be out of my current job and into something I love as soon as possible.

Would you recommend I do the Job Ready Guide - Javascript 2.0 first and use that to get a developer/programmer job, even though it it only involves a few of the courses that I will be taking for the data science guide? Or rather, go ahead and start the data science guide?

Again, thanks for your time

**Comment by P1xt** [comment]
If you eventually want to get into data science, I would start with the Python edition of the Job Ready Guide, because you'll want to be leaning towards knowing Python and R quite well to break into data science.

**Comment by RyRyMc** [comment]
Awesome, thank you so much. Also from your experience, I have always read for the other developer jobs that a degree is never officially required because you can always have a resume with more experience than the person with a degree. Does that also apply to the data science field, even though it has more math and science required?

**Comment by P1xt** [comment]
There will always be some jobs that exclude anyone without a degree.

But, there are other jobs that won't. Data science is no exception.

If you learn the material well, and develop a deep portfolio demonstrating that you can do the work, there will be jobs you're qualified for. But, for data science, it's going to take a lot of work to get to that point. Likely far less time than getting a degree would take though :smile:

**Comment by RyRyMc** [comment]
Awesome! Thank you so much! That is a lot more encouraging than what I have been reading from others.

**Comment by P1xt** [comment]
If I could give you one tip, it would be this - focus like a laser study your ass off so that you become knowledgeable and great at whatever you want someone else to pay you to do, so that hiring you will be an easy decision. 

That will always be a more productive use of your time than surfing the internet looking for people to tell you you're doing the right thing - 95%+ of the opinions you find will be "sour grapes" from people who didn't put in enough work to become great, or even good, developers and are pissing about in everyone else's wheaties because their lazy arse didn't impress anyone in an interview.

Don't worry for now about "will I be able to get a job" - that's not today's worry. Today's worry is "how hard can I study to ensure that one day I have enough provable expertise to show I am worthy of a job".

**Comment by RyRyMc** [comment]
That sounds like a good plan. Thanks, I needed to hear that.
