### ISSUE TITLE
Choice between Think Java and Think Python?

### ISSUE THREAD

**Issue by RishiSpeets** [P1xt/p1xt-guides#59]
There's a _Think Python: How to Think Like a Computer Scientist_ book which, as far as I've seen, covers the same ground as Think Java. Perhaps it's an idea to offer a choice between Think Java and Think Python. Multiple listed courses like Software Construction and Algorithms use Java. Some more exposure to Python might be nice.

What do you think @P1xt ?

**Comment by P1xt** [comment]
The "Think Python" book is actually in the JR Python and Data Science guides.

Think Java is where it is precisely because it immediately precedes two algorithms courses that are taught entirely using Java - I won't replace it there, or show alternatives, Think Java is where it is in the guide precisely because a Java review is absolutely necessary for what comes right after.

**Comment by RishiSpeets** [comment]
That makes sense. Thanks for sharing the reasoning behind your choice!
