### ISSUE TITLE
Python Guide

### ISSUE THREAD

**Issue by RyRyMc** [P1xt/p1xt-guides#60]
Is CS50 missing from the Python guide for any specific reason?

**Comment by P1xt** [comment]
Yes, it's replaced by the more Python-centric alternative (MIT's 6.001/6.002) which tackles the same CS topics (not quite, but at least a fair number of them) while using Python throughout (instead of Scratch, C, JavaScript, and Python) so, while in general CS50 is better, for a deep Python focus, the MIT sequence is better.

**Comment by AliMahmoud7** [comment]
Hi @P1xt, Should we take both of them?

**Comment by P1xt** [comment]
If you're following the Python guide, then yes take both 6.001 and 6.002 - they're both in the guide.

**Comment by AliMahmoud7** [comment]
Ok, I'm working on the Python guide but I mean both (CS50 and the two MIT courses).

**Comment by P1xt** [comment]
CS50 isn't in the Python guide...

**Comment by AliMahmoud7** [comment]
Yes, I know that. I'm just asking Should I take CS50 - as an extra course on python guide - for more benefits after finishing MIT 6.001 course or this will be useless?
Thanks in advance.

**Comment by P1xt** [comment]
CS50 is a fantastic course - However, if your focus is Python, I would finish the ENTIRE Python guide first and save CS50 for when you've finished the Python guide and moved on to one of the other (like the CS-WD) guides.

**Comment by AliMahmoud7** [comment]
Ok, Thanks!
