### ISSUE TITLE
Which guide should i choose?

### ISSUE THREAD

**Issue by shivendrarox** [P1xt/p1xt-guides#69]
Firstly thanks a lot for making these guides, I am currently doing udacity front end nanodegree, Even after completing the 1st module I am not feeling comfortable or confident for tackling the memory game project, I have almost completed this project's module. I think your guides can help me but I am confused, can you tell which guide should I follow so that I can make most of my time while studying from your guides?

**Comment by luijoy** [comment]
As you are wanting to feel more confident in your front end nanodegree, the Javascript frontend path seems the best fit: https://github.com/P1xt/p1xt-guides/blob/master/job-ready-javascript-edition-2.0.md

"Goal: confident **frontend** web developer ready to apply for junior positions"

**Comment by P1xt** [comment]
First - there's nothing wrong with something being challenging, I would recommend tackling the project regardless of how comfortable or confident you think you are. The point to doing projects to reinforce and expand your learning isn't to do some super simple thing that was crazy easy for you - the point is to leverage what you do know, combine it with persistence and an attitude of "you shall not defeat me", suck it up and DO IT. Even if you don't know how. Even if it's scary. Even if you're not confident. Even if you're not comfortable. Do it anyway. You don't build confidence by building super simple easy stuff, you build confidence by building things you're not quite sure you know how to build and looking back and thinking 'I thought that was too hard for me, but I just proved that hard isn't too hard'.

Second - I don't recommend studying one of my guides at the same time you're doing a udacity nanodegree in order to supplement the nanodegree. Why? Because hopping from one thing to the other always looking for 'some other resource' to make stuff easier is procrastination of the highest form. Stop trying to make things easier and just suck it up, work your ass off, and finish your nanodegree before you go looking for another resource. One thing finished is better than 10 things started and never finished.

Third - I recommend the CSWD guide (for when you're done with the nanodegree)

**Comment by shivendrarox** [comment]
Thanks a lot p1xt! That really cleared the fog. I was having a lot of resources on my list like React native udemy courses, ebooks,frameworks etc. But I am leaving that all until I graduate from my nanodegree

**Comment by P1xt** [comment]
That's the trick @shivendrarox - pick one resource that will help move you towards your goal, then finish it. Over time, you end up closer and closer to achieving your goal, with a series of accomplishments along the way. "I finished, x, y, and z" is a lot more powerful a foundation to be working from than I started and didn't finish two dozen things".

**Comment by shivendrarox** [comment]
Thanks p1xt! 😄
