### ISSUE TITLE
paid books?

### ISSUE THREAD

**Issue by rna7** [P1xt/p1xt-guides#88]
Would you recommend any paid books in additional to the paths set?

I can see that Eric Elliot's Programming Javascript Applications is no longer free but is this books still worth reading? 
His name pops up alot when looking at Javascript 'experts'

If you do recommend paid books as optional, which other books would you recommend?

Thanks you for great paths also.

**Comment by P1xt** [comment]
The one paid book I would consider prior to finishing an entire guide is Cormen's Introduction to Algorithms. That said, personally, I would finish an entire guide, step by step - rather than looking for other stuff to do on top of it. The entire goal of the guides is to lay out a step by step path that can be followed to 'get good' so you can avoid the procrastination technique of 'looking for something better or more' instead of actually doing the work ;)

**Comment by rna7** [comment]
Thank for solid advice. That seems to be the trap I've fallen into. At work at some point I will need to learn AWS, Mongo, node etc. But I still want to improve Javascript and core fullstack skills so I kept buying udemy courses and looked at MOOCs/guides.
I've read YDKJS before but I guess I will start at the beginning of your JS 3.0 and CS-WD guides and read YDKJS during free time at work and do CS50 at home. 

Thank you
